### ISSUE TITLE
Re-export chrono

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/gloo#100]
We could add a re-export of chrono here. The reason for this is that to use chrono in the browser, you must use a feature that isn't very discoverable (I spent about 30 mins getting chrono working). We could re-export with the feature turned on by default.

**Comment by hamza1311** [comment]
This is an issue with chorno and it documentation, which seems to have been fixed. From ["Features" section in their README](https://github.com/chronotope/chrono#features)

> `wasmbind`: Enable integration with wasm-bindgen and its `js-sys` project

It clearly states what's needed for wasm so I'm closing this issue.
