### ISSUE TITLE
Timeouts/Intervals could take `Duration`s

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/gloo#101]
They could convert the duration to an f64 of milliseconds before passing to js.

**Comment by Pauan** [comment]
The range of `setTimeout` and `setInterval` is `i32` (the max is `2,147,483,647`). And their precision is milliseconds.

On the other hand, `Duration` has nanosecond precision, and its range is `u128` (the max is `340,282,366,920,938,500,000,000,000,000,000,000,000`)

I think it's somewhat misleading to convert a number with such a huge range into a number with such a small range.
