### ISSUE TITLE
Question: achieving small WASM

### ISSUE THREAD

**Issue by schell** [rustwasm/gloo#108]
The readme states
> Small: Small code size for faster page loads. No accidentally pulling in all of the panicking and formatting infrastructure. Users shouldn't have to make a trade off between using Gloo libraries and having small Wasm binaries.

but I don't see anything explicitly about compilation or code size in the guide. Where can I find out more about this?

**Comment by Pauan** [comment]
This is the current best resource for small Wasm sizes: https://rustwasm.github.io/docs/book/reference/code-size.html

As far as gloo goes, it mostly means using `unwrap_throw` (or `expect`).

**Comment by schell** [comment]
Thanks! `unwrap_throw` is new to me!

**Comment by Pauan** [comment]
(To clarify, `unwrap_throw` is defined [here](https://docs.rs/wasm-bindgen/0.2.58/wasm_bindgen/trait.UnwrapThrowExt.html#method.unwrap_throw). It's the same as `unwrap`, except it doesn't panic, and it always uses a fixed static message, so there's no formatting involved.)
