### ISSUE TITLE
Help running browser tests

### ISSUE THREAD

**Issue by dakom** [rustwasm/gloo#111]
I try `wasm-pack test crates/timers --headless --firefox`

It doesn't seem to run any tests. Adding a failing test to `crates/timers/tests/web.rs` does not cause a failure.

What am I doing wrong?

**Comment by dakom** [comment]
Whups - didn't mean to ultimately file this as a bug. my bad! it's a question :) (unless maybe it is a bug?)

**Comment by dakom** [comment]
Am I the only one encountering this?

**Comment by Pauan** [comment]
The tests are currently feature-gated behind the `futures` feature, so you have to use `wasm-pack test crates/timers --headless --firefox -- --features futures`

Or you can use `-- --all-features` instead, which probably makes more sense.
