### ISSUE TITLE
Think about how to handle shared utility stuff

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/gloo#112]
I'm thinking specifically about the code that was added to handle the case that the api is available in both the `Window` and the `Worker` scopes. It seems like it might be nice to share that code between crates, which would require a kind of internal `utils` crate.

Interested to hear people's thoughts.

**Comment by Pauan** [comment]
I've been planning to write an RFC about that, it should be done Soon™.

**Comment by hamza1311** [comment]
Done in https://github.com/rustwasm/gloo/pull/155
