### ISSUE TITLE
Naming things is hard 

### ISSUE THREAD

**Issue by cricket007** [rustwasm/gloo#115]
### Steps to Reproduce

1. Go to a search engine 
2. Type `github gloo`
3. Scroll down to multiple results 
4. Not see this repo towards top

### Expected Behavior

I expect this not to be confused with something else

https://github.com/solo-io/gloo

**Comment by Pauan** [comment]
It's the 5th result on DuckDuckGo and Google, right below Facebook's Gloo.

I agree that naming is hard, but it's pretty much impossible to come up with truly unique names, especially if the name is short and memorable.

Even Rust itself has this problem (it's easily confused with both metal oxidation *and* the Rust video game).

**Comment by Pauan** [comment]
I'd also like to note that it's the *first* result if you search for `rust gloo` (which is far more precise than `github gloo`).

Many Rust libraries have the same name as non-Rust libraries, so it's often useful to put `rust` into the search terms.

**Comment by cricket007** [comment]
Fair enough 😅
