### ISSUE TITLE
...what kind of modular toolkit, though?

### ISSUE THREAD

**Issue by workingjubilee** [rustwasm/gloo#118]
### Describe the Bug

The README.md describes gloo as a "A modular toolkit for building fast, reliable Web applications and libraries with Rust and Wasm" and mentions a few example contents. But it does not give a high-level overview of gloo's contents or consequence, leaving me with only those examples, so I am not sure if it can do anything more. This requires me to consult API docs or read the source in order to find out if it will Solve My Particular Problems. I am not sure what modules it gets modular with, or what tools are in the toolkit, and while hearing that it won't try to do what other libraries do is nice, I am not sure what it does do.

It describes several aspirational goals which is fine, and a grand perspective and some ideas, but I am not really sure what specific problems that I, as a prospective wasm app builder, would use it to solve, and most of the goals are ones I would expect would be had by any Rust application or library.

### Expected Behavior

Compare with https://reactjs.org/ which says, plainly, "a JavaScript library for building user interfaces" and then describes multiple features, namely: the style of the library (declarative), the goal of easy integration, and the choice to use component-based interfaces, and elaborates a little on how those are useful. A very high level description but still a bit useful if I don't know what React is.

Even better, https://jquery.com/ describes the problem it was created to address and its capabilities to address it with, with a laserlike focus. If I have felt this painpoint, ever, I would be very interested.

**Comment by Pauan** [comment]
Gloo is not like React or jQuery, it is actually a collection of libraries, and those libraries can do all sorts of things: date/time, timers, DOM events, file fetching and reading, databases, server network communication, logging, Chrome/Firefox extensions, etc.

That's why it's a "toolkit" and not a "library" or "framework": it's just a collection of useful APIs. Those APIs are usually high-level wrappers around web-sys. So the best we can do for an overview is to say, "we have useful stuff". If you have any suggestions for a better overview, I'd be glad to hear it.

**Comment by workingjubilee** [comment]
>  If you have any suggestions for a better overview, I'd be glad to hear it.

Pretty sure you just posted it!

> date/time, timers, DOM events, file fetching and reading, databases, server network communication, logging, Chrome/Firefox extensions, etc.

That's fine.

**Comment by HiruNya** [comment]
When I first went onto this repo, I didn't know what specific functionality it provided either so I'd like to suggest listing all the sub-crates from the [crates folder](https://github.com/rustwasm/gloo/tree/master/crates) in the readme with a small explanation as to what each sub crate does.

**Comment by TheButlah** [comment]
Hi, random github user perusing WASM crates here. Putting something similar to @Pauan's comment in the README and enumerating the various sub-crates/modules would be helpful to quickly grok what the library does.

**Comment by jquesada2016** [comment]
100% agree with @HiruNya. I also didn't know what the crate provided without digging in deeper.
