### ISSUE TITLE
Need a maintainer

### ISSUE THREAD

**Issue by Pauan** [rustwasm/gloo#119]
Since I am no longer contributing to Rust, somebody else will need to take over as the maintainer of this project.

If anybody is interested in that, please contact @alexcrichton (who is a Rust Wasm WG Core member).

**Comment by tomseattle** [comment]
Pauan, Would love the chance to help as maintainer. Sent email to Alex.

**Comment by Stupremee** [comment]
@jstarry I would also be ready to help you out with maintaining this project.

**Comment by tomseattle** [comment]
@jstarry Sounds good, lets coordinate on some of the open issues and also some of the documentation. It would good if we can co-maintain if thats possible,  thanks

**Comment by MATRIXKOO** [comment]
Still, need a maintainer?

**Comment by jstarry** [comment]
Great to have all this interest, I think the real need here is contributors. It would be great to assess the state of current open PR's and issues first. If merging PR's and publishing crates becomes the bottleneck, we can share maintainer responsibilities.

**Comment by MATRIXKOO** [comment]
Contributor sounds good too.

**Comment by jstarry** [comment]
@alexcrichton would you mind updating my role from what I think is "contributor" to "maintainer" so that I can another maintainer to this repo?

**Comment by alexcrichton** [comment]
Sure, I've bumped you to "admin" since you were already "maintainer"

**Comment by jstarry** [comment]
Much appreciated, thanks!

**Comment by hamza1311** [comment]
@alexcrichton, can you give me the permission to modify secrets in this repo. I need the permissions for #140 (see the [failing CI](https://github.com/rustwasm/gloo/runs/2926113072?check_suite_focus=true#step:4:10))

**Comment by alexcrichton** [comment]
If it's ok I'm trying to have a"hands-off" approach to this crate so I don't have to personally be on the hook for things. I think @jstarry should be an admin, so they should have all the requisite privileges for changing things?

**Comment by hamza1311** [comment]
> If it's ok I'm trying to have a"hands-off" approach to this crate so I don't have to personally be on the hook for things. I think @jstarry should be an admin, so they should have all the requisite privileges for changing things?

If I interpreted their message on discord correctly, them and I have same permissions that's why I pinged you. If @jstarry can do it, I'd be fine with that. Again, I apologize for pinging you. If you're fine with it, I wouldn't mind having admin permissions for this repo

**Comment by alexcrichton** [comment]
Hm if an admin can't add another admin perhaps this repository should be trasnferred out of the rustwasm org?

**Comment by hamza1311** [comment]
> Hm if an admin can't add another admin perhaps this repository should be trasnferred out of the rustwasm org?

I'd like to keep it in the org since that's one of its selling points. It's not that we need to do such things frequently. If you don't mind, can you check my permissions level?

**Comment by alexcrichton** [comment]
I flagged you as an admin yesterday, was that not enough though? (I don't have a ton of time to help debug this and figure things out...)

**Comment by hamza1311** [comment]
> I flagged you as an admin yesterday, was that not enough though? (I don't have a ton of time to help debug this and figure things out...)

Thank you very much. I didn't you did, just checked and everything worked out.

**Comment by hamza1311** [comment]
Hi, it's me again. It seems like I don't have permissions publish a new release of `gloo` and it's crates on crates.io. It would be great if anyone can grant me the missing permissions.

CC: @jstarry
