### ISSUE TITLE
[Question] Binding / calling async rust function on click event

### ISSUE THREAD

**Issue by Rochet2** [rustwasm/gloo#127]
I'm trying to bind an async rust function to an on-click event with wasm-bindgen and gloo.
However, I have not yet figured out how to do so.
Some of the JS API exposed through wasm-bindgen requires me to use JS promises at places and I am having issues with mixing these async and sync functions.

Here is what I try to do, however it does not work as is because the async function needs to be handled somehow.
I couldn't see how I could directly bind an async function to be the click handler.
```rust
#[wasm_bindgen]
pub fn bind_on_click() {
  let window = web_sys::window().unwrap();
  let document = window.document().unwrap();
  let body = document.body().unwrap();

  let button = document.create_element("button").unwrap().dyn_into::<web_sys::HtmlButtonElement>().unwrap();
  button.set_text_content(Some("Click me"));
  body.append_child(&button).unwrap();

  let handle = EventListener::new(&button, "click", move |_event| {
    my_async_func(); // somehow call async here
  });
  handle.forget();
}

async fn my_async_func() {
  // work
}
```

How can I call an async function on a button click?
Any help/pointers are appreciated.

**Comment by hamza1311** [comment]
You need to use `wasm_bindgen_futures::spawn_local` in the listener callback to run a Future as promise.

**Comment by Rochet2** [comment]
Thanks works fine 👍
