### ISSUE TITLE
Keep/host mdbook vs create a website

### ISSUE THREAD

**Issue by hamza1311** [rustwasm/gloo#135]
Gloo needs a web page. We have the following 2 options:
1. Keep the [current mdbook](https://github.com/rustwasm/gloo/tree/master/guide), bring it up to date and host it
2. Create a website like [Yew's](https://yew.rs)

I don't really see the downside of going with 2. We can even have a gloo-specific blog that way. Gloo isn't big enough that it needs a book. API docs exist on docs.rs, everything else can be on the website.

**Comment by jstarry** [comment]
That would really help with general awareness about gloo!

**Comment by hamza1311** [comment]
@jstarry, should I just go ahead and create the website then?

**Comment by hamza1311** [comment]
Since the current mdbook is basically empty, I think turning it into a website would be a better idea. There won't be enough content there to even call it a "book". 

I'll be making a site similar to https://yew.rs/ and hosting it at https://gloo-rs.web.app/. I don't have a custom domain so it'll have to live at the free one google provides as part of a firebase project. If anyone wants to help out with that, that would be great.

**Comment by hamza1311** [comment]
I created the site. Here's the [preview URL](https://gloo-rs--site-preview-pb9mfx2j.web.app/). Thoughts?

There's a couple of things that jumped out:
1. We need to stop copying docs as READMEs. It messes up the links.
2.  We need more/better docs
