### ISSUE TITLE
Logo/icon for Gloo

### ISSUE THREAD

**Issue by hamza1311** [rustwasm/gloo#143]
Gloo project needs an icon/logo. 

Unfortunately, creating icons isn't my expertise so any help would be appreciated.

**Comment by voidpumpkin** [comment]
What about a green spiky-yew resembling crab? :D

**Comment by voidpumpkin** [comment]
![image](https://user-images.githubusercontent.com/32368314/143917176-7e7d3401-54cf-4b1f-9b17-eb676d48935c.png)

+

![image](https://user-images.githubusercontent.com/32368314/143917206-c58c368e-907c-4dc0-8e60-1957a5bcf3fb.png)


?

**Comment by hamza1311** [comment]
If you can design the SVG then I would be happy to use it...

**Comment by Dom-1** [comment]
<img width="703" alt="Screen Shot 2022-02-02 at 1 31 41 AM" src="https://user-images.githubusercontent.com/18057702/152111965-61ce3f19-45e7-46d3-b8ab-8e45d5a9fc78.png">
Just a quick prototype, what do you think? :D

**Comment by hamza1311** [comment]
@Dom-1 I like it. Should I just put it on or do you have some improvements in mind?

**Comment by hamza1311** [comment]
@Dom-1 I think it's better without a hat. If you can improve shading, that would be nice. 

It doesn't matter how it's made to me. A SVG is all that's needed. If you can PR that, that would be great.

You'll replace the default files [here](https://github.com/rustwasm/gloo/tree/master/website/static/img) with your creation and update the config file:
https://github.com/rustwasm/gloo/blob/a46a3e51520bd9200c6244f0c89c49034fe11b0d/website/docusaurus.config.js#L12
https://github.com/rustwasm/gloo/blob/a46a3e51520bd9200c6244f0c89c49034fe11b0d/website/docusaurus.config.js#L20

If you could update the color scheme as well, that would be great:
https://github.com/rustwasm/gloo/blob/a46a3e51520bd9200c6244f0c89c49034fe11b0d/website/src/css/custom.css#L8-L18

**Comment by Dom-1** [comment]
Motion to close this as a PR has been merged. :)
