### ISSUE TITLE
`Blob::new(&[u8])` makes an unnecessary copy

### ISSUE THREAD

**Issue by Liamolucko** [rustwasm/gloo#150]
The implementation of `BlobContents` for `&[u8]` uses `Uint8Array::from` to make a `Uint8Array` to pass to `Blob::new`. That method creates a copy of the slice, which is then immediately passed to `Blob::new`, which creates another copy of the `Uint8Array`. The first copy isn't necessary, because it can instead pass `Blob::new` a `Uint8Array` view into wasm memory. `Uint8Array::view` is unsafe, because the returned `Uint8Array` allows mutating the immutable buffer and has no lifetime, but it's fine to pass to `Blob::new`.

As a downside, this would require making `BlobContents::into_jsvalue` unsafe, because it would allow other code outside of `gloo` to invoke `Uint8Array::view` safely. I don't think it's really meant to be used outside of `gloo` anyway, though.

**Comment by hamza1311** [comment]
Thanks for the report. I like suggested optimization. Are you interested in fixing this yourself?

**Comment by Liamolucko** [comment]
Yes, I just wanted to get the go-ahead.
