### ISSUE TITLE
Make `gloo::timer`'s future-based design like stdlib

### ISSUE THREAD

**Issue by futursolo** [rustwasm/gloo#162]
## Summary

Make `gloo::timer`'s future-based API like `std` / `tokio`.

## Motivation

Why are we doing this? What problems does it solve?

This issue purposes to make gloo::timer's design more like Rust's standard library.

There was a similar discussion for the tokio library years ago about making the Tokio's sleep / timeout design to be similar to the standard library's design.

https://github.com/tokio-rs/tokio/issues/2770
https://github.com/tokio-rs/tokio/pull/2826

The rationale:
- It's more familiar with people coming from other Rust areas.
- The `std::thread::sleep` takes a `Duration` which is a better design than taking a number in millisecond in my opinion.
- `gloo::timer::sleep(Duration::from_secs(1)).await` is easier to understand and remember than `gloo::timer::TimeoutFuture::new(1000).await` for most people.

## Detailed Explanation

```rust
async fn sleep(duration: Duration) {
    // ...
}
```

## Drawbacks, Rationale, and Alternatives

Does this design have drawbacks?

It breaks compatibility.

Are there alternative approaches?

The current approach of `gloo::timer`.

Why is this design the best of all designs available?

This is a design that meets the expectation for people coming from both Rust and other common programming languages.

What prior art exists?

This is the design used by `std` and `tokio`.

**Comment by futursolo** [comment]
Sorry for filing an incomplete issue. I have updated the issue title and description.

**Comment by hamza1311** [comment]
I like this approach. How about we add a function for `sleep` in addition to the current API?

```rust
fn sleep(duration: Duration) -> TimeoutFuture {
    // ...
}

// somewhere else
sleep(Duration::from_secs(5)).await
// after 5 seconds 
```
