### ISSUE TITLE
`console_dbg` outputs wrong expression

### ISSUE THREAD

**Issue by Madoshakalaka** [rustwasm/gloo#172]
### Describe the Bug

`console_dbg!(anything)` will output `::std::format!("{:?}", v)` to the console

### Steps to Reproduce

producing code with Yew:

```rust
use yew::prelude::*;

#[function_component(App)]
fn app() -> Html {
    let a = 1;
    gloo_console::console_dbg!(a);
    gloo_console::console_dbg!(a + 1);
    html! {
    }
}

fn main() {
    yew::start_app::<App>();
}
```

### Expected Behavior

Should output `[src\main.rs:6] a = 1` and `[src\main.rs:7] a + 1 = 2` to the console.

### Actual Behavior

nuts:

![image](https://user-images.githubusercontent.com/44753941/143542705-d1dc2767-3f0b-441a-bc9f-3acc840c9655.png)

**Comment by hamza1311** [comment]
Welp... Looks like wrong expression is being `stringify`ed. Free free to submit a PR correcting it.

Also, do you know of a way to unit test this? I don't know how we'd read console output in tests run with wasm-bindgen

---

> ### Actual Behavior
> 
> nuts:

I'm sure Risu is proud

**Comment by Madoshakalaka** [comment]
> Also, do you know of a way to unit test this?

No clue, will ask some people...

**Comment by Madoshakalaka** [comment]
some more experienced web dev ( @eddieantonio ) says this:
> It's javascript; you could shadow the global console object and provide your own with a mock/spy/stub/whatever they're calling it these days and assert that it's being called with the right args

**Comment by hamza1311** [comment]
> some more experienced web dev ( @eddieantonio ) says this:
> > It's javascript; you could shadow the global console object and provide your own with a mock/spy/stub/whatever they're calling it these days and assert that it's being called with the right args

Interesting. I have no idea how that would happen in a wasm-bindgen test environment though

**Comment by Madoshakalaka** [comment]
> Free free to submit a PR correcting it.
working on it
