### ISSUE TITLE
Consider using bold styling for `console_dbg!` and `console!`

### ISSUE THREAD

**Issue by Madoshakalaka** [rustwasm/gloo#173]
## Summary

This is from [wasm_logger](https://docs.rs/wasm-logger/0.2.0/wasm_logger/)
![image](https://user-images.githubusercontent.com/44753941/143543106-3adbc19b-75b7-4f7d-9f16-5108f8c85205.png)

## Motivation

Bold style distinguishes the output from the path.

## Here's a tutorial on styling console output
https://www.telerik.com/blogs/how-to-style-console-log-contents-in-chrome-devtools

**Comment by hamza1311** [comment]
Would you like to PR a change making the file and line number bold?

**Comment by Madoshakalaka** [comment]
> Would you like to PR a change making the file and line number bold?

will do
