### ISSUE TITLE
Web Worker library

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#18]
* Spawning web workers
* Communicating via `postMessage`

(Note: this is for when we are *not* using shared memory and multithreading)

**Comment by Pauan** [comment]
> this is for when we are not using shared memory and multithreading

Why not both?

**Comment by fitzgen** [comment]
> Why not both?

Ah, yeah it is true that it could work in either situation. I expect that using a custom channel based on shared memory will be much faster than `postMessage` when multithreading is available but there is no technical reason why you couldn't still use `postMessage`. Although, the receiver thread would have to return the to event loop to be woken up by the `postMessage`...

**Comment by hamza1311** [comment]
I think basic the implementation would like this:

```rust
struct Worker<T> {
     raw: web_sys::Worker
     _data: PhantomData<T> 
};

impl<T> Worker {
    fn new(path: impl AsRef<str>) -> Self {
        let worker = web_sys::Worker::new(path)
        Self { worker, _data: PhantomData }
    }

    fn split(self) -> (Sender<T>, Reciever<T>) { ... }
}

impl<T> Stream for Worker<T> { ...  }

impl<T> Sink for Worker<T> { ...  }
```

This would of course be based on futures. Once this basic implementation is in place, all the bells and whistles (if needed) could be added later.

**Comment by hamza1311** [comment]
Done in #180
