### ISSUE TITLE
website: Links to `gloo-event`, should be `gloo-events`

### ISSUE THREAD

**Issue by tv42** [rustwasm/gloo#203]
### Describe the Bug

https://gloo-rs.web.app/ has a link to https://crates.io/crates/gloo-event which doesn't exist.
https://crates.io/crates/gloo-events does. The link text is also missing the trailing "s".

**Comment by hamza1311** [comment]
Would you like to PR a fix?

**Comment by Dom-1** [comment]
A PR (https://github.com/rustwasm/gloo/pull/207) has solved this issue. :)
