### ISSUE TITLE
Move website to separate repository

### ISSUE THREAD

**Issue by samcarey** [rustwasm/gloo#206]
I think the `website` folder and associated build machinery should be moved to a separate repository.
I think it is considered best practice to not mix the core Rust crate functionality with extras like the website.
See the Bevy set of repos for example, where the website is a separate repo from the Rust crates: https://github.com/bevyengine

This is currently impacting me because I recently downloaded several hundred Rust repositories for a vulnerability scan of my project's dependencies, and the only vulnerabilities found by my tool were those in https://github.com/rustwasm/gloo/blob/master/website/package-lock.json, which of course are not even required for using this crate.

Of course I can just delete the folder myself on my end, but I thought I'd let y'all know about this.

**Comment by hamza1311** [comment]
I can't do that. I don't have access to any other repository and I can't create one either. If I had access, I definitely would've made the the organization site and the wasm-bindgen better

**Comment by samcarey** [comment]
In that case, I would suggest that the website be moved to a repo in a different location (personal, or under a new Github org, as long as it's not under rustwasm) and just link to it in this repo's README.

**Comment by hamza1311** [comment]
That just makes it harder to keep it up to date. If we add any kind of documentation on the website, it would has to be committed to a different repository, contributors need to make multiple PRs, etc. There's cons of moving out the website outweigh the pros

**Comment by samcarey** [comment]
There's ways to decouple and automate it cleanly, but I can understand wanting to keep things simple. 

No problem! 
Thanks for contributing!
