### ISSUE TITLE
Revise docs for gloo_net::http::Request.method

### ISSUE THREAD

**Issue by hseeberger** [rustwasm/gloo#211]
Currently the dosc state "Note that the Origin header is not set on Fetch requests with a method of HEAD or GET.". This is not correct, though, because according to the [Fetch specification](https://fetch.spec.whatwg.org/#origin-header) the `Origin` header is used for all methods that have a "CORS" response tainting.

For more context, see [discussion 209](https://github.com/rustwasm/gloo/discussions/209).

**Comment by hamza1311** [comment]
Fixed in #212
