### ISSUE TITLE
gloo-net: `websocket` feature is missing Serde dependency if used with `default-features = false`

### ISSUE THREAD

**Issue by arctic-alpaca** [rustwasm/gloo#229]
### Describe the Bug

https://github.com/rustwasm/gloo/pull/222 introduced a dependency on `Serde` and `wasm-bindgen/serde-serialize` when using the `websocket` feature flag. The Cargo.toml file was not updated to reflect this.

**Comment by hamza1311** [comment]
Would you like to PR a fix?
