### ISSUE TITLE
Supporting module web worker in Gloo workers

### ISSUE THREAD

**Issue by arctic-alpaca** [rustwasm/gloo#238]
## Summary

I couldn't figure out a way to use [`WorkerType::Module`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/enum.WorkerType.html#variant.Module) workers with gloo workers. To create one, I added a method to the `WorkerSpawner` to pass [`WorkerOptions`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WorkerOptions.html#) and modified it to not use the JS shim used in the normal `spawn()` method.

## Motivation

Module workers support export/import which I need in a project.

## Detailed Explanation
I implemented what I need [here](https://github.com/arctic-alpaca/gloo/commit/233b0185659744cf6e6ffaaa99901de0f5cd7b4e), which seems to work so far.

## Drawbacks, Rationale, and Alternatives

I'm not very proficient with JS or how WASM works in the browser so there may very well be things i overlooked or missed.

## Unresolved Questions

I'm not sure this fits the current API since `spawn()` and `spawn_with_options_and_js_file()` expect different `path` parameters.
Currently I just copied the code from the `spawn()` method and modified it, this isn't really ideal since it duplicates the code.

**Comment by futursolo** [comment]
I am not sure what kind of benefit would it provide as the loader shim uses `importScript` anyways.

**Comment by arctic-alpaca** [comment]
This [blog post](https://web.dev/module-workers/) describes the differences between `classic` and `module` web workers better than I could. The `importScript` statement does not work with `module` web workers. 

The important part of the blog post for me is `Since module workers are standard JavaScript modules, they can use import and export statements.`. The Rust code I'm using exports multiple functions via `wasm_bindgen`. This creates multiple `exports` statements which don't seem to work with `classic` web workers.

A revised API to support `classic` (with shim) and `module` (without shim) web workers would probably be ideal but I'm currently not in a position to provide that.

**Comment by futursolo** [comment]
> The Rust code I'm using exports multiple functions via wasm_bindgen. This creates multiple exports statements which don't seem to work with classic web workers.

Try compile your worker with `--target=no-module` with `wasm-pack` or use `trunk`.
It should be an error with your build tool if it's trying to use `export` statement to export things when instructed not to do so.

In general, you should not have any export with Web Workers as these exported functions are not visible outside of the worker regardless of whether this is classic or module. You should send outputs back to your application.

**Comment by arctic-alpaca** [comment]
I'm using `wasm-pack` and using `--target=no-module` is probably a viable solution but at this time I need to use `--target=web`. The code running in the web worker is also used in a `module` context outside of the worker. Separating the functionality is not possible at this time.

A library I'm using is exporting a function via `wasm_bindgen` and removing this is currently also not an option.

Would you generally be open to supporting `module` web workers in `gloo-worker` or is this something that's out of scope?

**Comment by futursolo** [comment]
> I'm using wasm-pack and using --target=no-module is probably a viable solution but at this time I need to use --target=web. The code running in the web worker is also used in a module context outside of the worker. Separating the functionality is not possible at this time.

You can compile your worker with `--target=no-module` and `--target=web` for usage outside of worker.
In general, you will need 2 binaries as the worker will always attempt to register itself in `fn main()` and will fail when outside of a worker context.

> Would you generally be open to supporting module web workers in gloo-worker or is this something that's out of scope?

Personally, I would be in favour of holding this until Firefox supports it as I don't think ES module provides as big of a benefit when used in an isolated context (worker).
In the future, I think gloo-worker should support and eventually switch to ES Module as default.
But I don't think we are at that stage at the moment.

@hamza1311

**Comment by arctic-alpaca** [comment]
> You can compile your worker with --target=no-module and --target=web for usage outside of worker.
In general, you will need 2 binaries as the worker will always attempt to register itself in fn main() and will fail when outside of a worker context.

As far as my testing goes, I did not find any issues not using a `main()` function. The `run_worker()` function isn't used outside of a worker. Maybe I'm missing something here. This is what I did: 
Rust:
```rust
//... other stuff

#[wasm_bindgen]
pub fn run_worker() {
    console_error_panic_hook::set_once();

    MyWorker::registrar().register();
}
```
JS:
```javascript
import init, {run_worker} from "./my_worker.js"

async function run_in_worker() {
    await init();

    run_worker();
}

await run_in_worker();
``` 

> Personally, I would be in favour of holding this until Firefox supports it as I don't think ES module provides as big of a benefit when used in an isolated context (worker).
In the future, I think gloo-worker should support and eventually switch to ES Module as default.
But I don't think we are at that stage at the moment.

To be honest, I did not take browser compatibility into account. Your position sounds very reasonable to me.

**Comment by hamza1311** [comment]
> Personally, I would be in favour of holding this until Firefox supports it as I don't think ES module provides as big of a benefit when used in an isolated context (worker).

I agree here. Especially since we have a solution that works right now, browser compatibility is important. I'm fine with features that are supported only on the latest version but not having support for major browsers is a deal breaker

**Comment by arctic-alpaca** [comment]
As this isn't actionable at this time, I'll close the issue.
