### ISSUE TITLE
Proposal: Function Worker

### ISSUE THREAD

**Issue by futursolo** [rustwasm/gloo#251]
## Summary

This implemented was originally implemented in https://github.com/yewstack/yew/pull/2773 for Yew Agent.
I think this can also be provided to `gloo-worker` in a framework agnostic fashion (with the exception of SSR).

## Motivation

Previously the `gloo_worker::Worker` type implements an actor model which can be difficult for beginners.

This issue proposes 2 new worker types:

1. `oneshot`: For each input, a single output is produced.
2. `reactor`: A type of worker that operates receives inputs and produces outputs over a channel pair.

## Detailed Explanation

2 Procedural Macros are added:

```rust
#[oneshot]
async fn Squared(input: u32) -> u32 {
    input.pow(2)
}

#[reactor]
async fn SquaredOnDemand(rx: Receiver<u32>, tx: Sender<u32>) {
    while let Some(m) = rx.next().await {
        if tx.send(m.pow(2)).is_err() {
            break;
        }
    }
}
```

2 Spawner types are added as well:

```rust
// OneshotBridge
let squared_bridge = Squared::spawner().spawn();
assert_eq!(squared_bridge.run(2).await, 4);

// ReactorBridge
let (squared_tx, squared_rx) = SquaredOnDemand::spawner().spawn();

squared_tx.send(2);
// Schedules shutdown of bridge.
drop(squared_tx);

assert_eq!(squared_rx.next().await, Some(4));
assert_eq!(squared_rx.next().await, None);
```

### Drawbacks

The procedural macros will use boxed futures until `type_alias_impl_trait` becomes stable.

### Alternative Design

Functional workers can also be implemented using a method like [`tower::service_fn`](https://docs.rs/tower/0.4.13/tower/fn.service_fn.html). With this method, functional workers can be produced without boxing or `type_alias_impl_trait`.

However, this can cause issues with the current spawning method as workers are identified with a struct type.
(The original Agent v2 also uses context providers to identify agents. This method will produce an anonymous type and cannot be used to create context providers.)

## Unresolved Questions

- Should we name the functional workers something else other than `oneshot` and `reactor`?
- Should `gloo_worker::Worker` be renamed to something else to avoid confusion as there will be multiple worker types?

**Comment by hamza1311** [comment]
That's a great idea! I would be happy be merge any PRs implementing this. I have a couple of questions though:
- What's the difference between reactor and oneshot workers? I'd say calling the function for each message is better than passing the channel to the worker.
- Is there any benefit to using macros for this? I would prefer not using macros as they really mess up editors.

Also, it'd be _function_ workers not _function**al**_ workers. This was discussed when adding `#[function_component]` attribute to Yew: https://github.com/yewstack/yew/pull/1638#issuecomment-723362336 and I think that still applies here

**Comment by hamza1311** [comment]
Apologies for how long it took me to respond to this.  
For reactor workers, wouldn't it make more sense to have the function be called every time a message is sent? The fact that bridge lives on can be abstracted away. The worker implementation can hold on to the bridge and on every message, it will call the function is called and it's returned value is sent back.
The API can be:
```
#[worker(flavor = "oneshot")]
async fn Squared(input: u32) -> u32 {
    // called when a value run method is invoked
    input.pow(2)
}

#[worker(flavor = "reactor")]
async fn Squared(input: u32) -> u32 {
    // called when a value is sent to the channel
    input.pow(2)
}
```

Since specialization is not yet a thing, I'm fine with macros. Though it would be great if there wasn't a lot of macro-magic involved

**Comment by futursolo** [comment]
> For reactor workers, wouldn't it make more sense to have the function be called every time a message is sent?

A reactor worker is M:N, which means that both bridge and worker are free to send inputs and outputs at anytime.
An input does not guarantee an output vice versa.

I have included an example in #267 to demonstrate the reactor worker.

**Comment by hamza1311** [comment]
> A reactor worker is M:N, which means that both bridge and worker are free to send inputs and outputs at anytime.
> An input does not guarantee an output vice versa.

I understand input not requiring an output (where output is `()` and worker only does some computation). But if an output doesn't require an input, how is the worker called in the first place?  
The main difference (other than involvement of a bridge) is that the worker can be "recursive". right? It would be great to document that if that is the case

**Comment by futursolo** [comment]
> But if an output doesn't require an input, how is the worker called in the first place?

A reactor worker can start to create output without first receiving an input.
This is also possible with struct worker via the `fn connected()` lifecycle.

> The main difference (other than involvement of a bridge) is that the worker can be "recursive". right?

I am not sure what "recursive" means. The fundamental difference of oneshot worker and reactor worker is that reactor worker can receive any number of inputs and yield any number of outputs at a time they wish to.

Consider the example in #267:

```rust
 #[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
 pub enum ControlSignal {
     Start,
     Stop,
 }

 #[gloo::worker::reactor]
 pub async fn Prime(mut scope: ReactorScope<ControlSignal, u64>) {
     while let Some(m) = scope.next().await {
         if m == ControlSignal::Start {
             'inner: for i in 1.. {
                 // This is not the most efficient way to calculate prime,
                 // but this example is here to demonstrate how primes can be
                 // sent to the application in an ascending order.
                 if primes::is_prime(i) {
                     scope.send(i).await.unwrap();
                 }

                 futures::select! {
                 m = scope.next() => {
                     if m == Some(ControlSignal::Stop) {
                         break 'inner;
                     }
                 },
                 _ = sleep(Duration::from_millis(100)).fuse() => {},
                 }
             }
         }
     }
 }
```

The reactor worker will wait for an input of `ControlSignal::Start` (optional) before starting to create primes (2, 3, 5, 7...) every 100 milliseconds until it receives a `ControlSignal::Stop`. Primes will be sent to the bridge's stream. which it can read it from at anytime. I am not sure how this can be modeled without using Stream / Sink (provided via channels).

**Comment by rmsc** [comment]
"Me too"

As a beginner, my big complaint against the current API is that it's sync. This makes it extremely awkward to do a thing as simple as sending data through a WebSocket. It forced me to spawn an async task and feed it data through a channel.
