### ISSUE TITLE
Question re: gloo_worker 

### ISSUE THREAD

**Issue by SpanishPear** [rustwasm/gloo#259]
Hi!
Some questions re: `gloo_worker`

**Question 1**
In the provided examples, it seems that  `bridge.send` is [called twice, once in the function, and once inside a spawn_local](https://github.com/rustwasm/gloo/blob/master/examples/markdown/src/bin/example_markdown_app.rs#L32,L35).

Keeping only the spawn local works, but keeping the one inside the function body does not work. Keeping both calls twice. 
 
Is this done for any particular reason?

**Question 2**
Is there any way to not use the callback pattern, and to instead await on the value returned?  
I had hoped that 
```rust
spawn_local(async move {
    bridge.send(crate::agent::ToWorker::Ping);
    // We need to hold the bridge until the worker resolves.
    let promise = Promise::new(&mut |_, _| {});
    let a = JsFuture::from(promise).await;
    log::error!("{:?}", a);
});
```
would log the value, but it seems to not run. 
Is what I'm trying to achieve currently possible?

Thanks :D

**Comment by futursolo** [comment]
> Is this done for any particular reason?

No, I believe I have done it accidentally. The send outside of the spawned task can be removed safely.

> Is there any way to not use the callback pattern, and to instead await on the value returned?

You can use send the values into a channel in the callback and awaits the channel's receiver.
The promise was created as the worker will be destroyed if the bridge instance is not being held somewhere.
The promise will never resolve.

I have created #251 to consider function workers which also have a channel-based bridge.
(It creates a channel internally.)

**Comment by SpanishPear** [comment]
Ah, #251 sounds awesome ( I hadn't properly read through it until now ). Hoping the gloo folk get back to you!

Thanks for the response <3 Really appreciate all your work on the worker tech!! 

Gonna close this now, will submit a PR to fix the example as well :)
