### ISSUE TITLE
Send Blob to a Worker

### ISSUE THREAD

**Issue by hamza1311** [rustwasm/gloo#275]
## Problem

The `gloo_worker::Worker` trait's `Input` type has a `serde::Serialize` trait bound. `web_sys` types, including `Blob`, do not implement this trait.

## Context

I have a `Worker` that  processes images. The input of it is a `gloo_file::File` (which internally holds a `Blob`). `File` cannot implement `Serialize`  because it's inner fields do not

**Comment by futursolo** [comment]
You can use structured clone if you write a `gloo::worker::Codec` and implement the input and output type with `#[serde(skip)]` on the field with `web_sys::File`. You should be able to get around the Serialize and Deserialize requirement.

You can also read the image into a `Vec<u8>` before sending it to a Web Worker and send back as `Vic<u8>` or blob URL, as you have to convert the image into a base64 blob URL if you want to display or saving it anyways.

**Comment by hamza1311** [comment]
> You can use structured clone if you write a `gloo::worker::Codec` and implement the input and output type with `#[serde(skip)]` on the field with `web_sys::File`. You should be able to get around the Serialize and Deserialize requirement with a custom Codec.

I don't quite follow here. Do you have any example that for this? 

> You can also read the image into a `Vec<u8>` before sending it to a Web Worker and send back as `Vec<u8>` or blob URL, as you have to convert the image into a base64 blob URL if you want to display or saving it anyway.

I was trying to avoid the cost of serializing `Vec<u8>` and sending the bytes. The image may be multiple MBs and I didn't want to hide a potential clone behind the serialization

**Comment by yordanmadzhunkov** [comment]
I have a similar issue. I am trying to implement a yew front end application that uploads image file to a server. 
My back-end implementation supports multipart upload and I am able to upload images with curl from the command line.

I tried to serialize the image as array of u8 and whenever the post request size gets greater then 64kB, I run into some errors and I can't figure out how to continue forward.

It will be very helpful, if somebody provides with working example for this scenario using gloo

**Comment by thepackett** [comment]
I am also needing to send a file to a Worker and can't figure out a solution, or understand what futursolo is suggesting. Processing large files can take several seconds, even minutes when you have large data sets to process, and freezing the entire webpage for that duration is extremely undesirable. Using a webworker would be the perfect solution, if only Blobs could be serialized and deserialized.

**Comment by futursolo** [comment]
> take several seconds, even minutes when you have large data sets to process

IMHO, I do not believe this is the case as this means you are trying to send a very large amount data to the worker at one time. I think you will exhaust the available memory address before it freezes. WebAssembly is 32bit at the moment which means it will not have more than 4GB of available memory at any given time and bincode can encode / decode 4GB/s in about 1 second when I tested locally. I also do not think browsers would allow websites to to allocate this much resource without showing warnings that this tab is using a significant amount of resources.

Whether we support this or not, this is not a very desirable approach to use WebAssembly to process user data at the client side.

If you can process data in small chunks, then you can read it in small chunks and send it through to worker in small chunks.

However, I think we still should support it as it does help to improve user experience.

I would prefer https://github.com/cloudflare/serde-wasm-bindgen/issues/32 to be implemented and I was trying to help to implement it, but seems like its maintainers do have a different opinion on how it should be implemented. If they eventually get to implement this feature, this issue will be solved without changes to gloo-worker at all.
