### ISSUE TITLE
Example are swapped in the `JsValueSerdeExt` documentation

### ISSUE THREAD

**Issue by jbtrystram** [rustwasm/gloo#276]
Not a bug but a documentation issue: On the `JsValueSerdeExt` documentation, the `from_serde` example actually
calls `into_serde()`, and the example for `into_serde` is the other way around 

https://docs.rs/gloo-utils/latest/gloo_utils/format/trait.JsValueSerdeExt.html#tymethod.from_serde

**Comment by hamza1311** [comment]
Good catch! Would you like to PR a fix?
