### ISSUE TITLE
gloo-history: If a callback retrieves a Location, then any _with_state function can panic.

### ISSUE THREAD

**Issue by kinnison** [rustwasm/gloo#284]
### Describe the Bug

The `BrowserHistory` struct, presumably in an effort to not have a `T: Serialize+DeserializeOwned` trait bound on the `_with_state` functions, has a `RefCell` protected collection of states.  However, whenever a history change happens and the listeners are informed the borrow of that refcell remains held.  This means that, for example, a `replace_with_state()` call can end up with a listener hitting an already-borrowed panic.

This happens with `yew-router`'s `Navigator` support.  I produced a minimal reproduction example (attached) which uses Yew and Yew-Router.

### Steps to Reproduce

1. run up a yew project using the attached [`main.rs`](https://github.com/rustwasm/gloo/files/10418091/main.rs.txt) (dependencies on `yew` and `yew-router`)
2. Open the project in your browser and click the button, notice the panic in the console.

### Expected Behavior

I did not expect to see a panic.  Instead the counter should increment when the button is clicked, and using the links and back-forward in the browser should preserve counter states.

### Actual Behavior

I get a `panicked at 'already mutably borrowed: BorrowError', /home/dsilvers/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/gloo-history-0.1.2/src/browser.rs:226:34`

### Additional Context

I believe this is simply that the `.borrow_mut()` of the states is held too long.

**Comment by simbleau** [comment]
I can confirm the bug
