### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#29]
Thought I already did this but I guess not >.<

I'd like to do Azure pipelines since they have a higher level of parallelism at the free tier than travis ci. Also, they're not recently acquired by a sketchy, strip-it-down-for-parts company that laid off a ton of people.

**Comment by rylev** [comment]
@fitzgen this is done with #46. I think any further improvements should be separate issues.

**Comment by fitzgen** [comment]
Thanks!

**Comment by samcday** [comment]
I think this needs to be re-opened @fitzgen - the CI is only running `cargo test` and not running the integration tests

**Comment by fitzgen** [comment]
@samcday Yeah, we're fixing that in follow up PRs like #54
