### ISSUE TITLE
async wasm tests don't seem to actually do anything

### ISSUE THREAD

**Issue by carlsverre** [rustwasm/gloo#368]
### Describe the Bug

Currently the async tests in `net` use spawn_local, but don't actually wait for the spawned tasks to do anything. In addition, since spawn_local should always be run on the next microtask - the wasm instance will exit before any of the spawn_locals fire.

You can "test" this by adding an assert!(false) somewhere in the spawn_local part of the test.

### Fix

To fix this, wasm_bindgen supports async tests: https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/asynchronous-tests.html

I fixed the websocket test in a quick way here: https://github.com/rustwasm/gloo/compare/master...carlsverre:gloo:feat-arraybuf

I tried a similar quickfix to the eventsource tests but discovered that the echo server in place is not handling cors - so that test is already broken. Unfortunately I don't have time right now to change the echo server / do more extensive work. Sorry about that.

**Comment by hamza1311** [comment]
Thanks for reporting! I would be happy to look at any PRs fixing the issue

**Comment by richardpringle** [comment]
@hamza1311, PTAL at #394
