### ISSUE TITLE
Use `Closure::once` in `gloo-timers`

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#39]
We can fix this `TODO`:

https://github.com/fitzgen/gloo/blob/ea02bfaaf5413b5e50cc6f74a882d97a9e164ee5/crates/timers/src/lib.rs#L113-L119

Since the linked PR merged and there's been a wasm-bindgen release with the new API: https://docs.rs/wasm-bindgen/0.2.40/wasm_bindgen/closure/struct.Closure.html#method.once

**Comment by OddCoincidence** [comment]
I can do this
