### ISSUE TITLE
[history] Inconsitent type between gloo_history and gloo_utils

### ISSUE THREAD

**Issue by ctron** [rustwasm/gloo#426]
In `gloo_history` the API allows to set any type `T` as state. In `gloo_utils::history` it uses `JsValue`. I believe the latter one is closer to what the web actually is.

This becomes a problem when one wants to use `gloo_history` for setting the state, but then consume it somewhere else. As the type is then wrapped into a `HistoryState` struct, which is private to the crate.

I believe there should be a way to use `JsValue` too.

**Comment by ctron** [comment]
What is also worth noting: it is not possible to get the actual value of the state, as it's hidden in an internal table of the `gloo_history::BrowserHistory` instance.

**Comment by futursolo** [comment]
This is an expected behaviour, `gloo_history` allows you to store Rust types, which cannot be passed back to JavaScript.

When you use `gloo_history`, it assumes that you will only use `gloo_history` and browser buttons to manipulate history.
Trying to use both `gloo_history` and `window.history` is not supported.

**Comment by ctron** [comment]
Right I understand that. Buy my ask is basically to provide a way to do it differently.

**Comment by futursolo** [comment]
> Right I understand that. Buy my ask is basically to provide a way to do it differently.

In this case, please use the propose design issue instead and not bug issue template and please follow the issue template.

**Comment by ctron** [comment]
> In this case, please use the propose design issue instead and not bug issue template and please follow the issue template. 

Template didn't seem to make sense in this case. And I though it was a bug because two gloo components provide an incompatible API.

**Comment by ctron** [comment]
So just closing the issue means I need to fork gloo?

**Comment by futursolo** [comment]
> And I though it was a bug because two gloo components provide an incompatible API.

gloo_history is a complete history implementation and gloo_utils provides convenient access to certain web_sys types.
They serve different purpose.

**Comment by ctron** [comment]
So you would not even accept a PR on this?

**Comment by futursolo** [comment]
> So you would not even accept a PR on this?

You can propose an updated API with the propose design issue template and describe what you want to do with the API.

However, how gloo_history interacts with `window.history` should be an implementation detail. gloo_history needs to work in non wasm environments as well, so I am not in favour to expose any JavaScript / Web specific API.
But that is the general idea and may change depending on the API design.

**Comment by hamza1311** [comment]
`gloo_utils::history()` returns a `web_sys` type, which of course takes JsValue. That API is not provided by gloo
