### ISSUE TITLE
File API Library

### ISSUE THREAD

**Issue by rylev** [rustwasm/gloo#47]
Let's make an idiomatic, Rust-y interface to the file API!

https://w3c.github.io/FileAPI/

**Comment by rylev** [comment]
@fitzgen I'd like to take this on. I think the mid-level API should be pretty straight forward translation of the raw APIs with the following changes:
* remove all JSValue's (e.g., translate exceptions to bespoke error types)
* callbacks take the appropriate closure types
* Builder types instead of overloaded constructor functions

Should I make an official proposal for this and expand on these points?

**Comment by fitzgen** [comment]
> Should I make an official proposal for this and expand on these points?

Yes please!

**Comment by fitzgen** [comment]
Now that #50 is merged, this is ready for implementation!

Were you planning on doing the implementation as well, @rylev?

**Comment by rylev** [comment]
Yep. I'm away for a few days but will do it at the end of the week
