### ISSUE TITLE
Need to republish / version bump gloo-net after upgrade to http v1.0

### ISSUE THREAD

**Issue by DylanRJohnston** [rustwasm/gloo#483]
Hey all, after #407 upgraded `gloo-net`'s dependency on http from v0.2.9 to v1.0 the minor version of this package was not bumped nor the changes published to crates.io. A significant portion of the ecosystem has since migrated onto http v1.0 and this is causing issues with incompatible struct types, increased build times, and increased binary sizes.

**Comment by ranile** [comment]
gloo-net 0.6.0 has been released 🎉
