### ISSUE TITLE
Web Sockets library

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#7]
Let's make an idiomatic, Rust-y interface for working with Web Sockets!

**Comment by thedodd** [comment]
I apparently didn't see this issue when I created #49. Sorry! My search string was `websocket` without a space, that's probably why I missed it.

@fitzgen what would you like to do with this issue?

**Comment by fitzgen** [comment]
I think it is fine to leave it open as a sort of meta issue until we've got some websockets API(s) in Gloo that we are happy with.

**Comment by derekdreery** [comment]
@Pauan I've had a first go at implementing websockets following the gloo pattern [in a branch](https://github.com/derekdreery/gloo/tree/websocket). It works with tests, but I'm not sure the design is perfect yet. Specifically, I'm not sure how much to use the traits from `futures` (`Stream` and `Sink`) and how much to just use our own methods. I'll try to write up the different possibilities with their tradeoffs, but in the mean time I thought you might be interested in my first draft implementation.

**Comment by derekdreery** [comment]
I'm just goona bump this thread and make a request for comments on the proposal #113. I'm especially interested in whether it satisfies your use-case? When I have used websockets, it has always been for essentially JSON-RPC, where you send either notifications (messages without a response) or requests (messages that expect a response). I'm wondering in particular if any users have performance requirements and whether this design satisfies them, and also whether the API is as simple as it could be?

**Comment by hamza1311** [comment]
I'm gonna close this issue in favor of #49 as that one has more discussion/activity.
