### ISSUE TITLE
Create a compelling example for the README

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#80]
We have a placeholder right now, but we should have something cool!

Ideally it would use multiple `gloo` crates (probably via `gloo::whatever` re-exports).

Maybe using timers and events? Suggestions welcome!

**Comment by fitzgen** [comment]
+cc @yoshuawuyts, master of tiny-but-compelling code snippets

**Comment by yoshuawuyts** [comment]
@fitzgen ohhh, hi!

I was thinking perhaps showing off the websocket capabilities might be fun:

```rust
use futures::prelude::*;
use futures::BufReader;
use gloo::WebSocket;

#[Derive(serde::Deserialize)]
struct Message {
    id: usize,
}

#[runtime::main]
async fn main() {
    let socket = WebSocket::connect("/ws").await;
    let socket = BufReader::new(socket);

    #[runtime::for_await]
    for string in socket.lines() {
        let msg = Message.parse(string);
        println!("message #{} received", msg.id);
    }
}
```

This is not _quite_ feasible right now, but I think the interaction between Serde's structured serialization + composable abstractions over web APIs might make some things click for what Gloo is about! (:

**Comment by yoshuawuyts** [comment]
Oh, maybe this was too ambitious. It'd make for a really fun demo tho, haha. Perhaps logging to the console in a set loop gives a good idea of how things currently feel (:
