### ISSUE TITLE
Give the guide some content

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/gloo#81]
The guide is pretty much empty. It should have *something* in it.

--------------------

Straw proposal:

* Make every gloo crate use [`cargo readme`](https://github.com/livioribeiro/cargo-readme) to generate its `gloo/crates/whatever/README.md` from its module documentation

* Use [`mdbook`'s file include feature](https://rust-lang-nursery.github.io/mdBook/format/mdbook.html#including-files) to include these as a section in the guide

This would get us a good amount of documentation in all the places users expect it to be, without multiplying the maintenance effort.

Thoughts?

----------------------

+cc @David-OConnor @Pauan @yoshuawuyts @rylev

**Comment by Pauan** [comment]
That sounds fine to me. I agree that the guide's contents should probably match with the crate's docs.

**Comment by David-OConnor** [comment]
The current crates are fairly straightforward, and are easy to understand from the comments in code and examples. The guide will be more relevant once complex, interacting crates are included.
