### ISSUE TITLE
How to keep EventListener in memory?

### ISSUE THREAD

**Issue by dakom** [rustwasm/gloo#84]
Here is a "hello world" lib.rs, building off the [rust-webpack-template](https://github.com/rustwasm/rust-webpack-template) but with `HtmlButtonElement` added to the web-sys dependencies.

It only adds a button to the dom, and attaches a gloo EventListener to it:

```
use gloo_events::EventListener;
use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{console};

// When the `wee_alloc` feature is enabled, use `wee_alloc` as the global
// allocator.
#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

// Called by our JS entry point to run the example.
#[wasm_bindgen]
pub fn run() -> Result<(), JsValue> {
    set_panic_hook();

    let window = web_sys::window().expect("should have a Window");
    let document = window.document().expect("should have a Document");

    let body = document.body().expect("should have a body");
    let body: &web_sys::Node = body.as_ref();

    let btn: web_sys::HtmlButtonElement = document.create_element("button")?.dyn_into()?;
    btn.set_text_content(Some("click me"));

    body.append_child(&btn)?;

    let evt_listener = EventListener::new(&btn, "click", move |e| {
        console::log_1(&JsValue::from_str("got click"))
    });

    Ok(())
}

fn set_panic_hook() {
    // When the `console_error_panic_hook` feature is enabled, we can call the
    // `set_panic_hook` function to get better error messages if we ever panic.
    #[cfg(feature = "console_error_panic_hook")]
    console_error_panic_hook::set_once();
}

```

The problem,is that the EventListener goes out of scope and gets dropped - even though the node continues to exist on the DOM.

I could add this:

```
Box::new(evt_listener).forget();
```

But then I'd be leaking memory...

What's the recommended solution to this problem?

Should there be a higher-level API that somehow associates EventListeners with the existence of the element on the DOM, i.e. relate it somehow to append_child / remove_child?

**Comment by Pauan** [comment]
> Should there be a higher-level API that somehow associates EventListeners with the existence of the element on the DOM, i.e. relate it somehow to append_child / remove_child?

Yes, those higher-level APIs are things like virtual DOM.

**Comment by dakom** [comment]
OK cool :)

> fn remove(self) {}

And this works because it'll consume self, thereby also consuming `_on_click` and dropping it all when the function finishes?

**Comment by Pauan** [comment]
> And this works because it'll consume self, thereby also consuming _on_click and dropping it all when the function finishes?

Yes, exactly. So you don't need to touch `_on_click` at all (which is why `EventListener` is so great). That's also why it has the leading `_`, because otherwise Rust would complain that the `on_click` property is never used.

**Comment by dakom** [comment]
Thanks for the great summary! Closing this issue for now..

**Comment by Pauan** [comment]
P.S. You don't need to use `Box::new(evt_listener).forget()`, you can just use `evt_listener.forget()`
